

###

http://localhost:3344/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE2NjEyNTU5ODIsImV4cCI6MTY2MTM0MjM4MiwiYXVkIjoiaHR0cHM6Ly9uaWtvbGF2LnJzLyIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiNjJjYzRhNjZjODgyZTEyNmVlOTk0N2E4IiwianRpIjoiNTUzZWJkMDctNzI4MS00NTM5LWE1NWItNTMyOTBkNzUyOTllIn0.NEHfl-6Fe6XSwasCuaVHp0wm0t05fmWbkjLuMfLchzg

###
